title = "Git Guild"
baseurl = "http://deginner.com/"
languageCode = "en-us"

[params]
  # Meta parameters.
  language = "en"
  encoding = "utf-8"
  keywords = ["Python", "JavaScript", "Decentralized", "Decentralization", "System D", "Systeme D", "Blockchain", "open source"]
  description = "Open source software development for decentralization, blockchains and system D"

  # Top section of the website.
  topAnchor = "top"
  logo = "http://i.imgur.com/MINlVoa.png"
  title = "Git Guild"
  tagline = "Open Source Governance"

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Contact"
  weight = 4
  identifier = "contact"
  url = "/contact"
